### ISSUE TITLE
Default tab width doesn't match Prettier

### ISSUE THREAD

**Issue by thewilkybarkid** [joedeandev/prettier-plugin-nginx#7]
The docs mention that it follows Prettier default, but it doesn't (it's set to 4, not 2).

**Comment by jxddk** [comment]
I could have been more clear in the documentation: the option for `tabWidth` is the same (that is, the same identifier for the configuration option is used). However, the default for that option in this project is 4 spaces, as this matches the style used in NGINX's own documentation.
